module.exports.cors_error = 'cors'
module.exports.teapot_error = 'the server responded with a status of 418'
module.exports.media_error = 'media'
module.exports.videojs_error = 'videojs'
module.exports.playlist_error = 'playlist'
module.exports.broadcaster = 'iptv2022.com'